version: '3.8'

services:
  codegpt-api:
    container_name: codegpt-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - AUTH_TOKEN=${AUTH_TOKEN}
    volumes:
      - .:/usr/src/app
      - /Users/stefano.galassi/tmp:/usr/src/tmp
